### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by bhralz** [kaylode/image-inpainting#1]
Thanks for the brilliant implementation at first
but its running cant continued for some reasons:
need files such as:
./datasets/facemask_segmetation/annotations/train.csv'
...
please put them or at least give a step by step guide on how to complete running.
waiting to hear from you,

best regards.

**Comment by kaylode** [comment]
> Thanks for the brilliant implementation at first
> but its running cant continued for some reasons:
> need files such as:
> ./datasets/facemask_segmetation/annotations/train.csv'
> ...
> please put them or at least give a step by step guide on how to complete running.
> waiting to hear from you,
> 
> best regards.

Thank you for your question.
For the dataset preparation steps i will update to README later. Simply, What I did was downloaded the CelebA dataset, sampled ~30k images, cropped them to size 512x512, then generated masks for each of them (together with binary segmentation masks). After that I splitted them into train/val set and save their file paths to .csv file. 
However this synthesis dataset is only for research purpose,  if you want to apply to real world task, you would need other datasets.

**Comment by bhralzz** [comment]
Thanks for your kindly replying
actually could you please share the files you used or setting tuned in your project? 
please repeat the scenario on a small sampled dataset then sharing generated files and settings?

please attach them if possible (or upload them in google drive), so those can be helpful in running the total scenario and then adapting on another dataset.

best regards

**Comment by bhralzz** [comment]
Thanks for your kindly replying.
As I understand for general flow of the work each section can be automated (segmentation and unmasking)
maybe it would be fully automated just after setting datasets' path in .yaml files
right?

**Comment by bhralz** [comment]
Thanks for your kindly replying.
Could you please share a sample of CSV files and their content format?
best regards

**Comment by bhralz** [comment]
Dear Kaylode,
Actually, I need to run the project in its default mode (with your default setting).
Please, if you can, supply the complete scenario.
Waiting to hear from you.
Thanks for your help.

**Comment by kaylode** [comment]
Ok i have updated the preparation steps. Please read and try again. If you have any question, feel free to ask.

**Comment by bhralzz** [comment]
Thanks for your reply.
It is good in this form and process.

**Comment by bhralzz** [comment]
Thanks for your reply.
It is good in this form and process. 
finally, it is running without a problem now but is not going to train models and save them for use in infer function (for removing the mask from a face) as I checked.

Am I wrong? I ran in the following order:

**cfg1 = Config(f'./configs/segm.yaml')
trainer = UNetTrainer(cfg1)

cfg2 = Config(f'./configs/facemask.yaml')
trainer = Trainer(cfg2)**

Could you please check that?
Waiting to hear from you.
Best Regards

**Comment by bhralz** [comment]
Thanks for your reply.
It is good in this form and process.
finally, it is running without a problem now but is not going to train models and save them for use in infer function (for removing the mask from a face) as I checked.

running on the pytorch 1.7

Am I wrong? I ran in the following order:

**cfg1 = Config(f'./configs/segm.yaml')
trainer = UNetTrainer(cfg1)

cfg2 = Config(f'./configs/facemask.yaml')
trainer = Trainer(cfg2)**

Could you please check that?
Waiting to hear from you.
Best Regards

**Comment by kaylode** [comment]
> Thanks for your reply.
> It is good in this form and process.
> finally, it is running without a problem now but is not going to train models and save them for use in infer function (for removing the mask from a face) as I checked.
> 
> running on the pytorch 1.7
> 
> Am I wrong? I ran in the following order:
> 
> **cfg1 = Config(f'./configs/segm.yaml')
> trainer = UNetTrainer(cfg1)
> 
> cfg2 = Config(f'./configs/facemask.yaml')
> trainer = Trainer(cfg2)**
> 
> Could you please check that?
> Waiting to hear from you.
> Best Regards

what are the errors?

**Comment by bhralz** [comment]
File "D:\prjs\BHR\Prjs\Face_mask_detection\Codes\991027\image-inpainting-main\unet_trainer.py", line 120, in train_epoch
    for idx, batch in enumerate(self.trainloader):

  File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()

  File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)

  File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()

  File "D:\ANC\envs\FR_K_P\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "D:\ANC\envs\FR_K_P\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\ANC\envs\FR_K_P\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "D:\ANC\envs\FR_K_P\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "D:\ANC\envs\FR_K_P\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

TypeError: 'NoneType' object is not callable

**Comment by bhralz** [comment]
Dear Kaylode,
Did you find any solution for the above error?

**Comment by bhralz** [comment]
based on searching in the net,
maybe it depends on the python version? I am on python 3.6, a source of error?

**Comment by kaylode** [comment]
> File "D:\prjs\BHR\Prjs\Face_mask_detection\Codes\991027\image-inpainting-main\unet_trainer.py", line 120, in train_epoch
> for idx, batch in enumerate(self.trainloader):
> 
> File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 352, in **iter**
> return self._get_iterator()
> 
> File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
> return _MultiProcessingDataLoaderIter(self)
> 
> File "D:\ANC\envs\FR_K_P\lib\site-packages\torch\utils\data\dataloader.py", line 801, in **init**
> w.start()
> 
> File "D:\ANC\envs\FR_K_P\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> 
> File "D:\ANC\envs\FR_K_P\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> 
> File "D:\ANC\envs\FR_K_P\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> 
> File "D:\ANC\envs\FR_K_P\lib\multiprocessing\popen_spawn_win32.py", line 65, in **init**
> reduction.dump(process_obj, to_child)
> 
> File "D:\ANC\envs\FR_K_P\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> 
> TypeError: 'NoneType' object is not callable

sorry for the late reply, I've just finished my final term. 
I managed to run the repo code without any error. I suggest you check whether the paths in the csv file or the folder structure is correct (because I see that the errors come from dataloader, you should check if the image is opened successfully).  
If that is not the case, maybe it is the Pytorch/Python version.

**Comment by bhralz** [comment]
Thanks for your kindly replying.
I checked the code again, it's going inside dataset_seg.py in if statement
if os.path.isfile(mask_path):
    self.fns.append([img_path, mask_path])
as it examines file existence in the path and goes inside the if statement (so it seems that the path is correct!)

but it was not going into __getitem__ function at all (where reads the image files)
__getitem__ not called

however, I should check all the processes again.

thanks for your kindly replying.

**Comment by bhralzz** [comment]
Dear Kaylode
as I know image reading is done inside getitem.
Where is this function called inside other function?
and 
which is your python version?

**Comment by bhralzz** [comment]
I checked all the processes again but the error exists yet.
Also, I tried python 3.7
Could you please introduce a fast communication way in a private mode?

**Comment by bhralzz** [comment]
Dear Kaylode,
The problem is solved correcting paths also migrating to python 3.7.
How about testing trained network? 
using simple_image_inpainting.ipynb reached error: cannot import name 'vgg19'
also, how about its parallelism with multiple gpus?
Thanks for all of your help.

**Comment by bhralzz** [comment]
1- Is there any section of code for testing the trained network for unmasking face images(s)?

**Comment by suruthibalakrishnan** [comment]
> Thanks for your kindly replying. I checked the code again, it's going inside dataset_seg.py in if statement if os.path.isfile(mask_path): self.fns.append([img_path, mask_path]) as it examines file existence in the path and goes inside the if statement (so it seems that the path is correct!)
> 
> but it was not going into **getitem** function at all (where reads the image files) **getitem** not called
> 
> however, I should check all the processes again.
> 
> thanks for your kindly replying.

hey did you solve it
