### ISSUE TITLE
Testing the trained model 

### ISSUE THREAD

**Issue by bhralz** [kaylode/image-inpainting#2]
Dear  Kaylode, Could you plz provide a section of code for testing the trained network for unmasking face images(s)?

**Comment by kaylode** [comment]
> Dear Kaylode, Could you plz provide a section of code for testing the trained network for unmasking face images(s)?

 Unfortunately, there are no metrics for evaluating the images generated by GAN. I have implemented the infer.py which is used for inference, you can use it to test the trained network

**Comment by bhralz** [comment]
OK,
Tnx
